# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     SampleConsoleApp/bin/Release/netcoreapp2.1\**\!(*.pdb|*.config)
     SampleConsoleApp/bin/Release/netcoreapp2.1\**\!(*.dll|*.json)
     /home/vsts/work/1/s/SampleConsoleApp/bin/Release/netcoreapp2.1/**\!(*.pdb|*.config)
     /home/vsts/work/1/s/SampleConsoleApp/bin/Release/netcoreapp2.1/**\!(*.dll|*.json)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

